name = 'Ethan'
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
print('Hello', name)
